### ISSUE TITLE
Координатная плоскость с сеткой и без нее

### ISSUE THREAD

**Issue by Tavisevik** [tkhirianov/kpk2016#10]
Отображать оси координат с масштабной сеткой или без нее.
coordinats_plane(flag)
True - отображать оси координат вместе с масштабной сеткой
False - отображать только оси координат

**Comment by ganilova** [comment]
Лучше сделать отдельные функции
1. Рисование осей 
2. Отрисовка сетки
Тогда можно комбинировать по необходимости

**Comment by Tavisevik** [comment]
Рисует координатные оси (добавлена функция) 
395734ddac2e31790322bbcad360f6254b62ef0c
def draw_axis(number):
Нарисовать оси координат  с подписями черным цветом, толщиной 2 пикселя
    number - вид подписи:
    0 - без подписей, 1 - только точка (0,0), 2 - единичный интервал, 3 - все числа
    подписи выводятся коричневым цветом
