### ISSUE TITLE
Добавить возможность указывать толщину линии

### ISSUE THREAD

**Issue by acidulcer** [tkhirianov/kpk2016#12]
Возможно в каких-то случаях и пригодится

**Comment by ganilova** [comment]
Лучше, если толщина будет зависеть от масштаба

**Comment by acidulcer** [comment]
толщина линии у черепахи имеет фиксированный размер от 1 до 10, поэтому 1) либо ограничиваем диапазон масштаба, который может использовать пользователь, и привязываем толщину линии к масштабу,  2) либо не привязываем толщину линии к масштабу

**Comment by acidulcer** [comment]
Добавил функцию изменения толщины линии Чертежника в диапазоне от 1 до 10. По умолчанию. толщина линии Чертежника = 1

Функция drawman_pen_size(pen_size)
