### ISSUE TITLE
Смотрел в записи, не понял что такое форк

### ISSUE THREAD

**Issue by fizitra** [tkhirianov/kpk2016#19]
Подскажите что такое форк и как его сделать?

**Comment by alexcigun** [comment]
RTFM
https://help.github.com/articles/fork-a-repo/

2016-07-15 21:01 GMT+03:00 fizitra notifications@github.com:

**Comment by alexcigun** [comment]
Или по-русски
http://zencoder.ru/git/fork-github/

2016-07-15 21:03 GMT+03:00 Alex Cigun alexcigun@gmail.com:

**Comment by fizitra** [comment]
Спасибо.
