### ISSUE TITLE
дайте ссылку на группу КПК в ВК

### ISSUE THREAD

**Issue by fizitra** [tkhirianov/kpk2016#20]
Так и не понял создали группу или нет? Если да, поделитесь ссылкой плз.

**Comment by Inna1306** [comment]
https://vk.com/info_courses_for_teachers - группа в  ВК

**Comment by alexcigun** [comment]
Обсуждение ГитХаб типо
https://new.vk.com/topic-96421085_34057063?offset=20

2016-07-15 21:49 GMT+03:00 Inna1306 notifications@github.com:

**Comment by fizitra** [comment]
Спасибо всем ответившим
