### ISSUE TITLE
Точка пересечения функций

### ISSUE THREAD

**Issue by Tavisevik** [tkhirianov/kpk2016#9]
Вычислить и построить на графике точку(и) пересечения двух графиков.
Выбор цвета для этой точки.
common_point_functions(f1, f2, color)

**Comment by Tavisevik** [comment]
Графики предварительно рисуются
def intersection_point(f1,f2,x_begin,x_end):
    eps = 0.001
    x_step = 0.0001
    set_color("red")

```
x = x_begin
while x <= x_end:
    if fabs(f1(x)-f2(x))< eps:
        pen_up()
        to_point(x,f2(x))
        pen_down()
        t.dot(5)
    x += x_step
```

**Comment by alexcigun** [comment]
А где описываются f1 b f2?

**Comment by Tavisevik** [comment]
def f1(x):    return x_x#  return -0.5_x_x -2_x+2 Также как мы делали на уроке    12.07.2016, 15:24, "Alex" notifications@github.com:А где описываются f1 b f2?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
